### ISSUE TITLE
LoadError: load error: ethon/curls/options -- java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by PetrKaleta** [typhoeus/ethon#126]
This happens time to time when requiring typhoeus. It was  not happening with previous version. Running on `jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 24.65-b04 on 1.7.0_67-b01 [darwin-x86_64]`, `OSX 10.11.5`

```
LoadError: load error: ethon/curls/options -- java.lang.NullPointerException: null
/app/vendor/bundle/jruby/2.3.0/gems/ethon-0.9.0/lib/ethon/curl.rb:2:in `<top>'
/app/vendor/bundle/jruby/2.3.0/gems/ethon-0.9.0/lib/ethon.rb:1:in `<top>'
/app/vendor/bundle/jruby/2.3.0/gems/ethon-0.9.0/lib/ethon.rb:15:in `<top>'
/app/vendor/bundle/jruby/2.3.0/gems/typhoeus-1.0.2/lib/typhoeus.rb:1:in `block in (root)'
/app/vendor/bundle/jruby/2.3.0/gems/typhoeus-1.0.2/lib/typhoeus.rb:2:in `block in (root)'
/app/vendor/bundle/jruby/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:1:in `(root)'
/app/vendor/bundle/jruby/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/app/vendor/bundle/jruby/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/app/vendor/bundle/jruby/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `block in require'
/app/vendor/bundle/jruby/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
```

**Comment by abiacco** [comment]
I have this error too, but not through rake, it's when i run my war under tomcat. And only sometimes.

--- System
jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.77-b03 on 1.8.0_77-b03 +jit [linux-x86_64]

--- Backtrace
LoadError: load error: ethon/curls/options -- java.lang.NullPointerException: null
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/ethon-0.9.0/lib/ethon/curl.rb:2
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/ethon-0.9.0/lib/ethon.rb:1
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/ethon-0.9.0/lib/ethon.rb:15
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/typhoeus-1.0.2/lib/typhoeus.rb:1
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/typhoeus-1.0.2/lib/typhoeus.rb:2
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/image_info-1.1.2/lib/image_info/processor.rb:1
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/image_info-1.1.2/lib/image_info/processor.rb:1
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/image_info-1.1.2/lib/image_info.rb:1
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/image_info-1.1.2/lib/image_info.rb:2
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/image_parser.rb:1
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/image_parser.rb:1
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/models/image.rb:1
           require at org/jruby/RubyKernel.java:944
  block in require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
   load_dependency at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240
           require at /WEB-INF/vendor/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274
             <top> at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/models/image.rb:2
           require at org/jruby/RubyKernel.java:944
   block in (root) at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/base.rb:1
              each at org/jruby/RubyArray.java:1593
   block in (root) at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/base.rb:4
              each at org/jruby/RubyArray.java:1593
            (root) at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/default/base.rb:1
            (root) at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/default/base.rb:1
             <top> at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/default/title.rb:1
           require at org/jruby/RubyKernel.java:944
             <top> at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/default/title.rb:1
           require at org/jruby/RubyKernel.java:944
            (root) at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scraper.rb:1
            (root) at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scraper.rb:7
             <top> at /WEB-INF/vendor/bundle/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/page.rb:1

**Comment by TheKidCoder** [comment]
I think this will be fixed in jRuby 9.1.3.0: https://github.com/jruby/jruby/issues/3999

**Comment by JasonLunn** [comment]
I see this intermittently on JRuby 9.1.6.0

**Comment by PetrKaleta** [comment]
Same here,  its happening again in JRuby 9.1.6.0
