### ISSUE TITLE
Support Ruby 3.0 / webrick 1.7.0

### ISSUE THREAD

**Issue by pvalena** [typhoeus/ethon#173]
Currently the tests fail for me with webrick-related error:

```
+ rspec spec
#<Thread:0x000055a87248e4f8 /builddir/build/BUILD/ethon-0.12.0/usr/share/gems/gems/ethon-0.12.0/spec/support/localhost_server.rb:75 run> terminated with exceptio>
/usr/share/gems/gems/rack-2.2.3/lib/rack/handler/webrick.rb:26:in `run': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from /builddir/build/BUILD/ethon-0.12.0/usr/share/gems/gems/ethon-0.12.0/spec/support/localhost_server.rb:46:in `boot'
        from /builddir/build/BUILD/ethon-0.12.0/usr/share/gems/gems/ethon-0.12.0/spec/support/localhost_server.rb:29:in `block in initialize'
        from /builddir/build/BUILD/ethon-0.12.0/usr/share/gems/gems/ethon-0.12.0/spec/support/localhost_server.rb:75:in `block in concurrently'

An error occurred in a `before(:suite)` hook.
Failure/Error: raise TimeoutError.new(error_message) if (Time.now - start_time) > timeout

Timeout::Error:
  Boot failed.
# ./spec/support/localhost_server.rb:89:in `wait_until'
# ./spec/support/localhost_server.rb:30:in `initialize'
# ./spec/spec_helper.rb:25:in `new'
# ./spec/spec_helper.rb:25:in `block (2 levels) in <top (required)>'

Finished in 10.05 seconds (files took 0.44725 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

```

When run from Fedora build system. _Note that we do not use Bundler to handle dependencies, as we use system ones._

**Comment by pvalena** [comment]
Note that typhoeus test suite suffers the same failure.

**Comment by jas0nmjames** [comment]
I'm not sure if this is related, but I'm having a problem when trying to build jekyll with ethon.

`bundle exec jekyll build[?1l>[?2004l

]2;bundle exec jekyll build]1;bundle]133;C;Configuration file: /Users/jasonjames/repositories/jas0nmjames/jas0nmjames.github.io/_config.yml
/usr/local/lib/ruby/gems/3.0.0/gems/ethon-0.12.0/lib/ethon/curls/classes.rb:35: [BUG] Bus Error at 0x00007f9a6b052d30
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]`

Please see attached log.
[log.log](https://github.com/typhoeus/ethon/files/5868229/log.log)

**Comment by voxik** [comment]
> I'm not sure if this is related, but I'm having a problem when trying to build jekyll with ethon.

This seems to be unrelated.

**Comment by jas0nmjames** [comment]
> > I'm not sure if this is related, but I'm having a problem when trying to build jekyll with ethon.
> 
> This seems to be unrelated.

Thank you @voxik
