### ISSUE TITLE
Seg Fault on Ubuntu 20.04 Arm64

### ISSUE THREAD

**Issue by cguess** [typhoeus/ethon#201]
Running on Ubuntu 20.04 Arm64 with Ruby 3.0.2 I'm getting a seg fault on what looks to be a `free`. See below for a stack trace:

```
/home/parallels/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus/request/actions.rb:22:in `get'
/home/parallels/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus/request/before.rb:26:in `run'
/home/parallels/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus/request/stubbable.rb:25:in `run'
/home/parallels/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus/request/block_connection.rb:31:in `run'
/home/parallels/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus/request/cacheable.rb:18:in `run'
/home/parallels/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:16:in `run'
/home/parallels/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ethon-0.14.0/lib/ethon/easy/operations.rb:44:in `perform'
/home/parallels/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ethon-0.14.0/lib/ethon/easy/operations.rb:44:in `easy_perform'

-- Machine register context ------------------------------------------------
 "x0: 0x0000aaaad39685d0 "x1: 0x0000aaaad3e09e88 "x2: 0x0000000000000000
 "x3: 0x0000000001000000 "x4: 0x0054652e0223419b "x5: 0x000000000054652e
 "x6: 0x0209c5b1007ed27d "x7: 0x000000000209c5b1 "x1: 0x0000000000000003
 "x1: 0x0000000000000009 "x2: 0x0000aaaad39685c0 "x2: 0x0000aaaad3e09e68
 "x2: 0x0000000000000000 "x2: 0x0000ffffaa5a4800 "x2: 0x0000aaaad39685c0
 "x2: 0x00000000000003e9 "x2: 0x0000000000000001 "x2: 0x00000000000003e9
 "x2: 0x0000aaaad39684f0 "x2: 0x0000ffffe9c013e0 "sp: 0x0000ffffe9c013e0
 "fa: 0x0020ffffaa5a507c

-- C level backtrace information -------------------------------------------
Segmentation fault (core dumped)

```

**Comment by cguess** [comment]
This is coming through using Capybara with a Selenium Chrome driver. The relevant is as follows when setting the base url to `instagram.com`

```
Capybara.default_driver = :selenium_chrome
Capybara.app_host = "https://instagram.com"
Capybara.default_max_wait_time = 15

module Zorki
  class Scraper
    include Capybara::DSL

    def login
      visit("/")
      # Check if we're redirected to a login page, if we aren't we're already logged in
      return unless page.has_xpath?('//*[@id="loginForm"]/div/div[3]/button')
    end
end
```

**Comment by cguess** [comment]
FYI just attempted this with Firefox on the same machine, so it's definitely not related to the browser being used.

**Comment by Zapotek** [comment]
Try: https://github.com/typhoeus/ethon/pull/207

**Comment by cguess** [comment]
@felipedmesquita I'd have to  build the test code again. I ended up with a workaround about 4 years ago.  If other people haven't reported it I think you can close the issue.

**Comment by felipedmesquita** [comment]
Ok! I think there's a good chance this has been fixed with any of the similar issues that were resolved. If anyone runs into a similar problem on modern ruby/licburl/ffi versions, please open a new issue. Thanks @cguess for your report.
