### ISSUE TITLE
Ruby-win64 support with libcurl-x64.dll

### ISSUE THREAD

**Issue by wutai3** [typhoeus/ethon#230]
Hi, I use typhoeus for ruby-win64 enviroment.

Because curl-x64 official dll is "libcurl-x64.dll", so DLL load have failed. https://curl.se/windows/

```
D:\>ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt]

D:\>ruby -e " require 'typhoeus'  "
D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/ffi-1.15.5-x64-mingw-ucrt/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'libcurl': �w�肳�ꂽ���W���[����������܂���B\r (LoadError)
.
Could not open library 'libcurl.dll': �w�肳�ꂽ���W���[����������܂���B\r
.
Could not open library 'libcurl.so.4': �w�肳�ꂽ���W���[����������܂���B\r
.
Could not open library 'libcurl.so.4.dll': �w�肳�ꂽ���W���[����������܂���B\r
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/ffi-1.15.5-x64-mingw-ucrt/lib/ffi/library.rb:99:in `map'
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/ffi-1.15.5-x64-mingw-ucrt/lib/ffi/library.rb:99:in `ffi_lib'
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/ethon-0.16.0/lib/ethon/curls/settings.rb:10:in `<module:Curl>'
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/ethon-0.16.0/lib/ethon/curls/settings.rb:3:in `<module:Ethon>'
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/ethon-0.16.0/lib/ethon/curls/settings.rb:2:in `<top (required)>'
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/ethon-0.16.0/lib/ethon/curl.rb:28:in `require'
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/ethon-0.16.0/lib/ethon/curl.rb:28:in `<module:Curl>'
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/ethon-0.16.0/lib/ethon/curl.rb:14:in `<module:Ethon>'
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/ethon-0.16.0/lib/ethon/curl.rb:9:in `<top (required)>'
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/ethon-0.16.0/lib/ethon.rb:16:in `require'
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/ethon-0.16.0/lib/ethon.rb:16:in `<top (required)>'
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `require'
        from D:/pkg/ruby/lib/ruby/gems/3.1.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
        from -e:1:in `require'
        from -e:1:in `<main>'
```

Could it change setting file below?

```
ethon/curls/settings.rb 

-   ffi_lib ['libcurl', 'libcurl.so.4']
+    ffi_lib ['libcurl', 'libcurl.so.4', 'libcurl-x64']
```

Thanks.

**Comment by eye942** [comment]
Does your suggested change work for you? 

For me, it looks like adding an entry for `libcurl-4` worked for me.
![image](https://user-images.githubusercontent.com/8443360/231578211-32545fdb-7354-41e5-8556-e4ba1d6791c1.png)

However, I'm using [msys2's ucrt version of curl](https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-curl?repo=ucrt64) via ridk on Windows 10.

**Comment by wutai3** [comment]
Hi, but  "libcurl-x64.dll" way also works. Which is pefer better?

+    ffi_lib ['libcurl', 'libcurl.so.4', 'libcurl-x64']
