### ISSUE TITLE
segmentation fault at operations.rb:30

### ISSUE THREAD

**Issue by yegor256** [typhoeus/ethon#233]
I'm getting this:

```
/usr/local/rvm/gems/ruby-3.0.1/gems/ethon-0.16.0/lib/ethon/easy/operations.rb:30: [BUG] Segmentation fault at 0x000000004006464c
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0032 p:---- s:0172 e:000171 CFUNC  :easy_perform
c:0031 p:0014 s:0167 e:000166 METHOD /usr/local/rvm/gems/ruby-3.0.1/gems/ethon-0.16.0/lib/ethon/easy/operations.rb:30
c:0030 p:0020 s:0163 e:000162 METHOD /usr/local/rvm/gems/ruby-3.0.1/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:16
c:0029 p:0025 s:0158 e:000157 METHOD /usr/local/rvm/gems/ruby-3.0.1/gems/typhoeus-1.4.0/lib/typhoeus/request/cacheable.rb:18
c:0028 p:0033 s:0153 e:000152 METHOD /usr/local/rvm/gems/ruby-3.0.1/gems/typhoeus-1.4.0/lib/typhoeus/request/block_connection.rb:31
c:0027 p:0041 s:0149 e:000148 METHOD /usr/local/rvm/gems/ruby-3.0.1/gems/typhoeus-1.4.0/lib/typhoeus/request/stubbable.rb:25
c:0026 p:0020 s:0144 e:000143 METHOD /usr/local/rvm/gems/ruby-3.0.1/gems/typhoeus-1.4.0/lib/typhoeus/request/before.rb:26
c:0025 p:0025 s:0140 e:000139 METHOD /usr/local/rvm/gems/ruby-3.0.1/gems/typhoeus-1.4.0/lib/typhoeus/request/actions.rb:22
...

-- Ruby level backtrace information ----------------------------------------
...
/usr/local/rvm/gems/ruby-3.0.1/gems/typhoeus-1.4.0/lib/typhoeus/request/actions.rb:22:in `get'
/usr/local/rvm/gems/ruby-3.0.1/gems/typhoeus-1.4.0/lib/typhoeus/request/before.rb:26:in `run'
/usr/local/rvm/gems/ruby-3.0.1/gems/typhoeus-1.4.0/lib/typhoeus/request/stubbable.rb:25:in `run'
/usr/local/rvm/gems/ruby-3.0.1/gems/typhoeus-1.4.0/lib/typhoeus/request/block_connection.rb:31:in `run'
/usr/local/rvm/gems/ruby-3.0.1/gems/typhoeus-1.4.0/lib/typhoeus/request/cacheable.rb:18:in `run'
/usr/local/rvm/gems/ruby-3.0.1/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:16:in `run'
/usr/local/rvm/gems/ruby-3.0.1/gems/ethon-0.16.0/lib/ethon/easy/operations.rb:30:in `perform'
/usr/local/rvm/gems/ruby-3.0.1/gems/ethon-0.16.0/lib/ethon/easy/operations.rb:30:in `easy_perform'
```

It's happening inside Docker, Ubuntu 20.04.

**Comment by yegor256** [comment]
This is how I fixed it:

```
$ apt-get install -y libcurl4-gnutls-dev
```
