### ISSUE TITLE
Ethon::Errors::Select: An error occured on select: 4

### ISSUE THREAD

**Issue by taqtiqa-mark** [typhoeus/ethon#31]
I'm encountering this error while using Typhoeus.  

I've logged it as a typhoeus issue: typhoeus/typhoeus#252

However, it might be better classed as a ethon issue?

**Comment by Zapotek** [comment]
I've never seen this on *nix, apart from when profiling, but I get it regularly on Windows + JRuby.

```
[2015-01-06 09:03:14 -0800] [Ethon::Errors::Select] An error occured on select: 10014
[2015-01-06 09:03:14 -0800] C:/jruby-1.7.18/lib/ruby/gems/shared/gems/ethon-0.7.2/lib/ethon/multi/operations.rb:128:in `set_fds'
[2015-01-06 09:03:14 -0800] C:/jruby-1.7.18/lib/ruby/gems/shared/gems/ethon-0.7.2/lib/ethon/multi/operations.rb:47:in `perform'
[2015-01-06 09:03:14 -0800] C:/jruby-1.7.18/lib/ruby/gems/shared/gems/typhoeus-0.6.9/lib/typhoeus/hydra/runnable.rb:15:in `run'
[2015-01-06 09:03:14 -0800] C:/jruby-1.7.18/lib/ruby/gems/shared/gems/typhoeus-0.6.9/lib/typhoeus/hydra/memoizable.rb:51:in `run'
```

It seems to be related to the amount of queued requests, you can find the magic number with:
```ruby
require 'typhoeus'

hydra = Typhoeus::Hydra.new

1000000.times do |t|
    t.times do |i|
        request = Typhoeus::Request.new( 'http://testhtml5.vulnweb.com' )
        request.on_complete do |response|
            p "#{t} - #{i}"
        end

        hydra.queue request
    end

    hydra.run
end
```

It's usually 38 queued requests in my case.

Using Windows 7, JRuby 1.7.18, curl 7.30.0, Ethon 0.7.2 and Typhoeus 0.6.9.

**Comment by i0rek** [comment]
Thanks for reporting @Zapotek. I am not sure I will be able to help with that one because I don't have a windows machine and because this seems like a tricky problem. I will keep it in mind and look through the sources.

**Comment by Zapotek** [comment]
This is negating a huge amount of effort I've put in in order to make my system run on MS Windows. So, I'll sort this out even if it kills me.

I don't have any FFI experience though so I'll be bugging you for stuff now and then.

Starting with now, is there a reason you're using `FFI.errno` as the error code in the [raised](https://github.com/typhoeus/ethon/blob/master/lib/ethon/multi/operations.rb#L128) exception and not the `code` returned by `Curl.select`?
Seems like knowing `select`'s return code would be very helpful in debugging this.

**Comment by Zapotek** [comment]
Ah, nevermind the question, I just read up on `select` docs in a bit more detail. :)

**Comment by Zapotek** [comment]
OK, made some more sense of things now.

On MS Windows `FFI.errno` will be one of: http://msdn.microsoft.com/en-us/library/windows/desktop/ms740668%28v=vs.85%29.aspx

In my case it is [WSAENOTSOCK](http://msdn.microsoft.com/en-us/library/windows/desktop/ms740668%28v=vs.85%29.aspx#WSAENOTSOCK):
> An operation was attempted on something that is not a socket. Either the socket handle parameter did not reference a valid socket, or for select, a member of an fd_set was not valid.

@taqtiqa-mark's error would probably be an "EINTR: Interrupted system call.".
The `libc` [docs](http://www.gnu.org/software/libc/manual/html_node/Error-Codes.html) suggest retrying the operation on `EINTR` instead of failing, so it may be worth updating `Ethon::Multi::Operations#set_fds`:
> Interrupted function call; an asynchronous signal occurred and prevented completion of the call. When this happens, you should try the call again.
>
> You can choose to have functions resume after a signal that is handled, rather than failing with EINTR; see Interrupted Primitives.

Will keep digging. :)

**Comment by Zapotek** [comment]
Also getting [WSAEFAULT](http://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx#WSAEFAULT):
> The Windows Sockets implementation was unable to allocate needed resources for its internal operations, or the readfds, writefds, exceptfds, or timeval parameters are not part of the user address space.

**Comment by Zapotek** [comment]
Getting the same behavior on Windows using MRI 2.1.5 as well.

**Comment by Zapotek** [comment]
@taqtiqa-mark In the case of `select`, `EINTR` is set when a signal was caught, maybe something tried to terminate the process during the run?

**Comment by Zapotek** [comment]
In addition, `max_concurrency` is playing some sort of role in this.
For example, if you queue 38 or more requests with a `max_concurrency` of less that 36 you don't get this error.

Maybe some [inappropriate reuse](http://curl.haxx.se/mail/lib-2009-11/0117.html) is going on?

**Comment by Zapotek** [comment]
Also, increasing the [size](https://github.com/typhoeus/ethon/blob/master/lib/ethon/curls/classes.rb#L17) of the `FDSet` array affects the situation similarly. By increasing the size of the array the problem goes away, until you also start increasing the amount of queued requests.

Moreover, the size of the `@fd_excep` FD array seems to fluctuate with each run of the same script. Is that normal?

@i0rek I'm just poking things to document what happens, no idea how to actually solve the problem; I can give you as many debugging data as I can though and hopefully that'll be enough for you to pinpoint the cause.

**Comment by Zapotek** [comment]
Erm, not to sound like a complete moron but shouldn't the [size](https://github.com/typhoeus/ethon/blob/master/lib/ethon/curls/classes.rb#L17) be set to `FD_SETSIZE`? 2048 for Windows, as the comment says?

**Comment by i0rek** [comment]
@Zapotek thanks for your work! You should try the latest `0.7.0`. It has a default for `nosignal: false`. That could help with the `EINTR`.
Re the `FDSet` size I am not sure. Maybe `64*uint` is enough for 2048 uints?

**Comment by Zapotek** [comment]
No worries, it's been interesting. :)

I'm a bit fuzzy on the FFI stuff but are you sure that the relevant layout means that we're setting an array of size `uint*64` and not an array of 64 `unit`s?

**Comment by Zapotek** [comment]
Btw, by size I meant the size of entries, not overall size of the array.

For example, see [FFI docs](https://github.com/ffi/ffi/wiki/Structs#char-arrays) vs [Windows fd_set](http://msdn.microsoft.com/en-us/library/windows/desktop/ms737873%28v=vs.85%29.aspx).

**Comment by i0rek** [comment]
Gotcha, you are right.
