### ISSUE TITLE
Ethon::Errors::Select (An error occured on select: 22)

### ISSUE THREAD

**Issue by semmin** [typhoeus/ethon#98]
Possibly related to: [https://github.com/typhoeus/ethon/issues/31](https://github.com/typhoeus/ethon/issues/31)

I get a weird Ethon error while running two parallel requests using `Typhoeus::Hydra`:

```shell
Ethon::Errors::Select (An error occured on select: 22):
  lib/company/api.rb:40:in `search'
  app/query_objects/search_topics_query.rb:15:in `search'
  app/controllers/topics_controller.rb:35:in `search'
```

The error occurs _in production environment only_ that is not opened to the world yet, so high load / high queued request number is not a problem here. The code that triggers the error:

```ruby
module Company
  class Api

    def initialize
      @search_url = 'http://' + Settings.search.host + '/'
      @spellcheck_url = 'http://' + Settings.search.spellcheck_host
      @logger = Rails.logger || Logger.new(STDOUT)
      @hydra = Typhoeus::Hydra.new
    end

    def search(opts)
      if opts.query.nil?
        yield []
      else
        search_api_request = search_request(opts)
        search_api_request.on_complete do |response|
          if response.success?
            @search_results = JSON.parse(response.body)
          else
            @logger.error("HTTP request to #{@search_url} failed: " + response.code.to_s)
            @search_results = {}
          end
        end

        spellcheck_request = spellcheck_request(opts)
        spellcheck_request.on_complete do |response|
          if response.success?
            @spellcheck = Nokogiri::XML(response.body)
          end
        end

        @hydra.queue search_api_request
        @hydra.queue spellcheck_request
        @hydra.run # <= error is triggered here

        yield @search_results, @spellcheck
      end
    end

    private

    def search_request(params)
      Typhoeus::Request.new(
          @search_url,
          method: :get,
          followlocation: true,
          timeout_ms: 10000,
          params: params,
          headers: { Accept: "application/json" }
        )
    end

    def spellcheck_request(params)
      Typhoeus::Request.new(
          @spellcheck_url,
          method: :get,
          followlocation: true,
          timeout_ms: 10000,
          params: {
            query: params[:query]
          }
        )
    end

  end
end

```

Again, the behaviour is very sporadic, and occurs *only in production*. Versions:

```
ruby 2.2.0p0
rails 4.2.0
typhoeus (0.7.0)
ethon (>= 0.7.1)
```

Works on OS X 10.9.4 with `curl 7.30.0 (x86_64-apple-darwin13.0) libcurl/7.30.0 SecureTransport zlib/1.2.5`

Doesn't work on `FreeBSD 10.1-STABLE-r273058 amd64` with `curl 7.36.0 (amd64-portbld-freebsd10.0) libcurl/7.36.0 OpenSSL/1.0.1i zlib/1.2.8 libssh2/1.4.3`

Currently, I deal with the issue by `begin ... rescue Ethon::Errors::Select`, but it's obviously a workaround solution, so any help/advice will be greatly appreciated. Thanks for the great library.

**Comment by i0rek** [comment]
@semmin thanks for reporting. Your code looks good. This is one of the more complicated bugs. I have very little time recently, but I will let you know as soon as I made progress on that.

**Comment by semmin** [comment]
@i0rek thanks for looking into it. Let me know if I can provide more info.

**Comment by semaperepelitsa** [comment]
This error is happening randomly on our FreeBSD server as well.

```
curl 7.47.1 (amd64-portbld-freebsd10.1) libcurl/7.47.1 OpenSSL/1.0.2h zlib/1.2.8
FreeBSD 10.1-RELEASE-p31
```

**Comment by dcws** [comment]
The issue is libffi having the wrong definition for time_t and suseconds_t; I am posting a fix to them now, and I am commenting on all of these open bugs that I can so other people can find it more quickly than I did.

The fix is to go to the libffi type definitions (in the ffi-VER/lib/ffi/platform/x86_64-freebsd/types.conf and ffi-VER/lib/ffi/platform/i386-freebsd/types.conf files) and update time_t (2 of them) and suseconds_t (2 of them to long instead of integer.

**Comment by felipedmesquita** [comment]
It seems https://github.com/ffi/ffi/pull/627 fixed this. Please open a new issue if the problem persists
